# Production configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=validate
spring.thymeleaf.cache=true

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/prehospitalcare
spring.datasource.username=your_username
spring.datasource.password=your_password
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect