from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
import io
import pandas as pd
import os
from datetime import datetime

# Headless chart generation config
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt

# Register a font that supports the Rupee symbol
try:
    font_path = "/usr/share/fonts/truetype/freefont/FreeSans.ttf"
    if os.path.exists(font_path):
        pdfmetrics.registerFont(TTFont('FreeSans', font_path))
        DEFAULT_FONT = 'FreeSans'
    else:
        DEFAULT_FONT = 'Helvetica'
except Exception:
    DEFAULT_FONT = 'Helvetica'

def generate_pdf_report(products, total_sales, total_profit, total_revenue, generated_by="SystemAdmin"):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    elements = []

    styles = getSampleStyleSheet()

    title_style = ParagraphStyle(
        'TitleStyle',
        parent=styles['Title'],
        fontName=f"{DEFAULT_FONT}-Bold" if DEFAULT_FONT == 'Helvetica' else DEFAULT_FONT,
        fontSize=18,
        spaceAfter=12
    )

    heading2_style = ParagraphStyle(
        'Heading2Style',
        parent=styles['Heading2'],
        fontName=f"{DEFAULT_FONT}-Bold" if DEFAULT_FONT == 'Helvetica' else DEFAULT_FONT,
        fontSize=14,
        spaceAfter=10
    )

    heading3_style = ParagraphStyle(
        'Heading3Style',
        parent=styles['Heading3'],
        fontName=f"{DEFAULT_FONT}-Bold" if DEFAULT_FONT == 'Helvetica' else DEFAULT_FONT,
        fontSize=12,
        spaceAfter=8
    )

    normal_style = ParagraphStyle(
        'NormalStyle',
        parent=styles['Normal'],
        fontName=DEFAULT_FONT,
        fontSize=10,
        spaceAfter=6
    )

    # Title & Metadata
    elements.append(Paragraph("SmartBiz Enterprise Intelligence Report", title_style))
    current_time = datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S UTC')
    metadata_text = f"<b>Generated By:</b> {generated_by} | <b>Date/Time:</b> {current_time}"
    elements.append(Paragraph(metadata_text, normal_style))
    elements.append(Spacer(1, 15))

    currency_symbol = '₹' if DEFAULT_FONT != 'Helvetica' else 'Rs.'

    # Executive Summary
    elements.append(Paragraph("Executive Summary", heading2_style))
    summary_text = f"""
    Total Revenue: {currency_symbol}{total_revenue:,.2f}<br/>
    Total Profit: {currency_symbol}{total_profit:,.2f}<br/>
    Total Sales: {total_sales} units<br/>
    Products Analyzed: {len(products)}
    """
    elements.append(Paragraph(summary_text, normal_style))
    elements.append(Spacer(1, 15))

    # Generate Matplotlib Chart headlessly
    chart_img_flowable = None
    if products:
        try:
            plt.style.use('dark_background')
            fig, ax = plt.subplots(figsize=(6, 3))
            fig.patch.set_facecolor('#1E293B')
            ax.set_facecolor('#0F172A')

            categories = [p.category or 'General' for p in products]
            sales = [p.sales for p in products]

            df_temp = pd.DataFrame({'Category': categories, 'Sales': sales})
            summed = df_temp.groupby('Category')['Sales'].sum().reset_index()

            ax.bar(summed['Category'], summed['Sales'], color='#3B82F6', edgecolor='#1E293B')
            ax.set_title('Category Sales Performance', color='#F8FAFC', fontsize=10, fontweight='bold')
            ax.set_ylabel('Sales Volume (Units)', color='#F8FAFC', fontsize=8)
            ax.tick_params(colors='#F8FAFC', labelsize=8)
            plt.xticks(rotation=15, ha='right')
            plt.tight_layout()

            chart_buf = io.BytesIO()
            plt.savefig(chart_buf, format='png', facecolor='#1E293B', bbox_inches='tight', dpi=150)
            chart_buf.seek(0)
            plt.close(fig)

            # Use ReportLab's Image Flowable
            chart_img_flowable = Image(chart_buf, width=350, height=175)
        except Exception as ce:
            print(f"Failed to generate PDF chart: {ce}")

    if chart_img_flowable:
        elements.append(Paragraph("Visual Sales Distribution", heading3_style))
        elements.append(chart_img_flowable)
        elements.append(Spacer(1, 15))

    # Product Table
    elements.append(Paragraph("Detailed Product Performance", heading3_style))
    data = [['Product', 'Category', 'Price', 'Stock', 'Sales', 'Profit']]
    for p in products:
        data.append([p.product_name, p.category or 'General', f"{currency_symbol}{p.price:.2f}", p.stock_quantity, p.sales, f"{currency_symbol}{p.profit:.2f}"])

    t = Table(data, colWidths=[130, 80, 70, 50, 50, 80])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0F172A')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.HexColor('#F8FAFC')),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, -1), DEFAULT_FONT),
        ('FONTNAME', (0, 0), (-1, 0), f"{DEFAULT_FONT}-Bold" if DEFAULT_FONT == 'Helvetica' else DEFAULT_FONT),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor('#F8FAFC')),
        ('TEXTCOLOR', (0, 1), (-1, -1), colors.HexColor('#0F172A')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.grey)
    ]))
    elements.append(t)
    elements.append(Spacer(1, 20))

    # AI Insights
    elements.append(Paragraph("AI-Generated Strategic Insights", heading3_style))
    insights = [
        "Revenue optimization recommended for underperforming categories.",
        "Causal analysis indicates marketing spend has a high multiplier effect on revenue growth.",
        "Maintain optimal stock buffers on high-velocity inventory to mitigate stock-out risks."
    ]
    for insight in insights:
        elements.append(Paragraph(f"• {insight}", normal_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer

def generate_excel_report(products):
    buffer = io.BytesIO()
    data = []
    for p in products:
        data.append({
            'Product Name': p.product_name,
            'Category': p.category or 'General',
            'Price': p.price,
            'Marketing Spend': p.marketing_spend,
            'Stock Quantity': p.stock_quantity,
            'Sales': p.sales,
            'Revenue': p.revenue,
            'Profit': p.profit,
            'Date': p.date
        })
    df = pd.DataFrame(data)
    with pd.ExcelWriter(buffer, engine='openpyxl') as writer:
        df.to_excel(writer, index=False, sheet_name='Business Report')
    buffer.seek(0)
    return buffer
